--  ===========================================================================
--  Script: perimeter.lua
--  Purpose: 
--      Excavate a volume of blocks. You can specify the boundaries of the
--      volume relative to the turtle.
--  Use: 
--      excavate [-l <left_boundary>] 
--          [-r <right_boundary>]
--          [-u <upper_boundary>]
--          [-d <lower_boundary>] 
--          [-f <forward_boundary>]
--          [-b <backward_bondary>]
--  Author: Sean Rice
--  Date: January 1st, 2021
--  ===========================================================================
